// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unicorns-can-fly.proto

/*
Package unicorns is a generated protocol buffer package.

It is generated from these files:
	unicorns-can-fly.proto

It has these top-level messages:
	StartRequest
	Response
*/
package unicorns

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartRequest struct {
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*StartRequest)(nil), "unicorns.StartRequest")
	proto.RegisterType((*Response)(nil), "unicorns.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Friend service

type FriendClient interface {
	StartChatApp(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Response, error)
}

type friendClient struct {
	cc *grpc.ClientConn
}

func NewFriendClient(cc *grpc.ClientConn) FriendClient {
	return &friendClient{cc}
}

func (c *friendClient) StartChatApp(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/unicorns.Friend/StartChatApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Friend service

type FriendServer interface {
	StartChatApp(context.Context, *StartRequest) (*Response, error)
}

func RegisterFriendServer(s *grpc.Server, srv FriendServer) {
	s.RegisterService(&_Friend_serviceDesc, srv)
}

func _Friend_StartChatApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).StartChatApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicorns.Friend/StartChatApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).StartChatApp(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Friend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unicorns.Friend",
	HandlerType: (*FriendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartChatApp",
			Handler:    _Friend_StartChatApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unicorns-can-fly.proto",
}

func init() { proto.RegisterFile("unicorns-can-fly.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xcd, 0xcb, 0x4c,
	0xce, 0x2f, 0xca, 0x2b, 0xd6, 0x4d, 0x4e, 0xcc, 0xd3, 0x4d, 0xcb, 0xa9, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x89, 0x2b, 0xf1, 0x71, 0xf1, 0x04, 0x97, 0x24, 0x16, 0x95, 0x04,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x71, 0x71, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x1a, 0xb9, 0x71, 0xb1, 0xb9, 0x15, 0x65, 0xa6, 0xe6, 0xa5, 0x08, 0xd9, 0x40, 0x55,
	0x39, 0x67, 0x24, 0x96, 0x38, 0x16, 0x14, 0x08, 0x89, 0xe9, 0xc1, 0x0c, 0xd0, 0x43, 0xd6, 0x2d,
	0x25, 0x84, 0x10, 0x87, 0x99, 0xa2, 0xc4, 0xe0, 0xc4, 0x14, 0xc0, 0x98, 0xc4, 0x06, 0xb6, 0xd8,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x7a, 0x6a, 0xde, 0x92, 0x00, 0x00, 0x00,
}
